(global-set-key (kbd "C-c /") 'ac-complete-filename)
(ac-config-default)
 (add-to-list 'ac-sources 'ac-source-filename)
 (setq ac-ignore-case nil)
 (add-to-list 'ac-modes 'enh-ruby-mode)
 (add-to-list 'ac-modes 'web-mode)
